src/model/Itinerario.java
package model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


@Entity
@Table(name="Itinerario")
public class Itinerario {
	
	@Id
	private int id;
	
	@Column(name = "id_Usuario")
	private int idUsuario;
	
	@Column(name = "id_Atraccion")
	private int idAtraccion;
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	public int getIdAtraccion() {
		return idAtraccion;
	}

	public void setIdAtraccion(int idAtraccion) {
		this.idAtraccion = idAtraccion;
	}

	public Itinerario() {

	}	

}

src/model/Producto.java
package model;


public abstract class Producto {
	
	
	private int id;
	
	
	private String nombre;
	
	
	public Producto() {

	}
	
	public void setId(int id) {
		this.id = id;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getId() {
		return id;
	}

	public String getNombre() {
		return nombre;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((nombre == null) ? 0 : nombre.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Producto other = (Producto) obj;
		if (nombre == null) {
			if (other.nombre != null)
				return false;
		} else if (!nombre.equals(other.nombre))
			return false;
		return true;
	}

	@Override
	public String toString() {
		return "nombre=" + nombre;
	}

	public abstract String tipoClase();

	public abstract String toStringArchivo();

	public abstract double calcularCostoFinal();

	public abstract double getCosto();

	public abstract double getTiempo();
	
	public abstract boolean tieneCupo();

	public abstract void comprado();

}

WebContent/itinerarios/list.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jstl/core_rt"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>


<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">

<head>
<meta charset="UTF-8">
<title>Itinerario</title>
<script
	src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!--BOOTSTRAP-->
<link rel="stylesheet"
	href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
<script
	src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
	integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
	crossorigin="anonymous"></script>
<script
	src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
	integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
	crossorigin="anonymous"></script>

<!-- Los iconos tipo Solid de Fontawesome-->
<link rel="stylesheet"
	href="https://use.fontawesome.com/releases/v5.0.8/css/solid.css">
<script src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>

<!-- Nuestro css-->
<link rel="stylesheet" type="text/css" href="static/css/user-form.css"
	th:href="@{/css/user-form.css}">
<!-- DATA TABLE -->
<script
	src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script
	src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
<link rel="stylesheet"
	href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
<link rel="stylesheet"
	href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">

</head>

<div class="container">
	<div class="mx-auto col-sm-13 main-section" id="myTab" role="tablist">
		<ul class="nav nav-tabs justify-content-end">
			<li class="nav-item"><a class="nav-link active" id="list-tab"
				data-toggle="tab" href="#list" role="tab" aria-controls="list"
				aria-selected="false">Lista Itinerarios</a></li>
		</ul>
		<div class="tab-content" id="myTabContent">
			<div class="tab-pane fade show active" id="list" role="tabpanel"
				aria-labelledby="list-tab">
				<div class="card">
					<div class="card-header">
						<h4>Itinerario de maravillas adquiridas por la tierra media</h4>
					</div>
					<div class="card-body">
						<div class="table-responsive">
							<table id="atracciones"
								class="table table-bordered table-hover table-striped">
								<thead class="thead-light">
									<tr>
										<th>Nombre</th>
										<th>Costo</th>
										<th>Tiempo</th>
										<th>Cupo</th>
										<th>Tipo de atracción</th>
									</tr>
								</thead>
								<tbody>
									<c:forEach items="${atracciones}" var="at">
										<tr>
											<td><c:out value="${at.nombre}" /></td>
											<td><c:out value="${at.costo}" /></td>
											<td><c:out value="${at.tiempo}" /></td>
											<td><c:out value="${at.cupo}" /></td>
											<td><c:out value="${at.tipoAtraccion.nombre}" /></td>
										</tr>
									</c:forEach>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		<a id="button_id" href="./inicio">Salir</a>
	</div>
</div>
</html>